CREATE DATABASE SoftUni;

USE SoftUni;

CREATE TABLE Towns (
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(100) NOT NULL
);

CREATE TABLE Addresses (
	Id INT PRIMARY KEY IDENTITY,
	AddressText VARCHAR(100) NOT NULL,
	TownId INT FOREIGN KEY REFERENCES Towns(Id)
);

CREATE TABLE Departments (
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(100) NOT NULL
);

CREATE TABLE Employees (
	Id INT PRIMARY KEY IDENTITY,
	FirstName VARCHAR(100) NOT NULL,
	MiddleName VARCHAR(100),
	LastName VARCHAR(100) NOT NULL,
	JobTitle VARCHAR(100) NOT NULL,
	DepartmentId INT FOREIGN KEY REFERENCES Departments(Id),
	HireDate DATETIME2,
	Salary DECIMAL(6, 2) NOT NULL,
	AdressId INT FOREIGN KEY REFERENCES Addresses(Id)
);